import type { Entry } from "./types"
import { format, subDays, addDays } from "date-fns"

function randomId(): string {
  return `entry-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

function randomDate(daysBack: number): string {
  const d = subDays(new Date(), Math.floor(Math.random() * daysBack))
  return format(d, "yyyy-MM-dd")
}

function futureDate(daysAhead: number): string {
  const d = addDays(new Date(), Math.floor(Math.random() * daysAhead) + 1)
  return format(d, "yyyy-MM-dd")
}

// Using new ID format: "person-1", "person-2", or "shared"
export function generateMockEntries(): Entry[] {
  const entries: Entry[] = [
    // Recurring income
    {
      id: randomId(),
      amount: 4200,
      date: format(subDays(new Date(), 5), "yyyy-MM-dd"),
      type: "income",
      recurrence: "monthly",
      category: "Salary",
      merchant: "Employer Direct Deposit",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 3800,
      date: format(subDays(new Date(), 5), "yyyy-MM-dd"),
      type: "income",
      recurrence: "monthly",
      category: "Salary",
      merchant: "Partner Employer",
      assignedTo: "person-2",
    },
    // Recurring shared expenses
    {
      id: randomId(),
      amount: 1450,
      date: futureDate(3),
      type: "expense",
      recurrence: "monthly",
      category: "Rent / Mortgage",
      merchant: "Property Management Co.",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 120,
      date: futureDate(10),
      type: "expense",
      recurrence: "monthly",
      category: "Utilities",
      merchant: "Electric Company",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 65,
      date: futureDate(10),
      type: "expense",
      recurrence: "monthly",
      category: "Utilities",
      merchant: "Internet Provider",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 89.99,
      date: futureDate(15),
      type: "expense",
      recurrence: "monthly",
      category: "Insurance",
      merchant: "State Farm",
      assignedTo: "shared",
    },
    // Recurring personal - person-1
    {
      id: randomId(),
      amount: 15.99,
      date: futureDate(25),
      type: "expense",
      recurrence: "monthly",
      category: "Subscriptions",
      merchant: "Netflix",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 10.99,
      date: futureDate(18),
      type: "expense",
      recurrence: "monthly",
      category: "Subscriptions",
      merchant: "Spotify",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 14.99,
      date: futureDate(12),
      type: "expense",
      recurrence: "monthly",
      category: "Entertainment",
      merchant: "Disney+",
      assignedTo: "person-2",
    },
    {
      id: randomId(),
      amount: 9.99,
      date: futureDate(20),
      type: "expense",
      recurrence: "monthly",
      category: "Subscriptions",
      merchant: "iCloud Storage",
      assignedTo: "person-1",
    },
    // Recurring personal - person-2
    {
      id: randomId(),
      amount: 49.99,
      date: futureDate(8),
      type: "expense",
      recurrence: "monthly",
      category: "Health & Fitness",
      merchant: "Gym Membership",
      assignedTo: "person-2",
    },
    {
      id: randomId(),
      amount: 199,
      date: randomDate(30),
      type: "expense",
      recurrence: "yearly",
      category: "Subscriptions",
      merchant: "Amazon Prime",
      notes: "Annual membership",
      assignedTo: "shared",
    },
    // One-time expenses
    {
      id: randomId(),
      amount: 45.5,
      date: randomDate(10),
      type: "expense",
      recurrence: "none",
      category: "Dining Out",
      merchant: "Olive Garden",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 132.8,
      date: randomDate(7),
      type: "expense",
      recurrence: "none",
      category: "Groceries",
      merchant: "Whole Foods",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 28.9,
      date: randomDate(14),
      type: "expense",
      recurrence: "none",
      category: "Dining Out",
      merchant: "Chipotle",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 67.42,
      date: randomDate(20),
      type: "expense",
      recurrence: "none",
      category: "Shopping",
      merchant: "Target",
      assignedTo: "person-2",
    },
    {
      id: randomId(),
      amount: 89.95,
      date: randomDate(30),
      type: "expense",
      recurrence: "none",
      category: "Shopping",
      merchant: "Amazon",
      notes: "Household supplies",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 35,
      date: randomDate(5),
      type: "expense",
      recurrence: "none",
      category: "Transportation",
      merchant: "Shell Gas Station",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 22.5,
      date: randomDate(3),
      type: "expense",
      recurrence: "none",
      category: "Entertainment",
      merchant: "AMC Theatres",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 95.6,
      date: randomDate(15),
      type: "expense",
      recurrence: "none",
      category: "Groceries",
      merchant: "Trader Joe's",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 15,
      date: randomDate(8),
      type: "expense",
      recurrence: "none",
      category: "Health & Fitness",
      merchant: "CVS Pharmacy",
      assignedTo: "person-2",
    },
    {
      id: randomId(),
      amount: 52.3,
      date: randomDate(25),
      type: "expense",
      recurrence: "none",
      category: "Dining Out",
      merchant: "Sushi Palace",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 500,
      date: randomDate(2),
      type: "expense",
      recurrence: "none",
      category: "Savings",
      merchant: "Transfer to Savings",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 78.3,
      date: randomDate(18),
      type: "expense",
      recurrence: "none",
      category: "Groceries",
      merchant: "Costco",
      assignedTo: "shared",
    },
    {
      id: randomId(),
      amount: 250,
      date: randomDate(45),
      type: "income",
      recurrence: "none",
      category: "Miscellaneous",
      merchant: "Freelance Payment",
      notes: "Logo design project",
      assignedTo: "person-1",
    },
    {
      id: randomId(),
      amount: 42.99,
      date: randomDate(12),
      type: "expense",
      recurrence: "none",
      category: "Miscellaneous",
      merchant: "Office Depot",
      notes: "Printer ink",
      assignedTo: "person-2",
    },
  ]

  return entries
}
